// DiagnosticsPanel.tsx — Live signal monitor overlay.
// Rendered inside the 320×240 canvas widget area, on top of the dashboard.
// In simulation mode: values are generated by useLiveSignals (oscillating).
// When connected to a device: values come from USB telemetry (firmware pushes every ~200ms).

import { useLiveSignals } from '../../hooks/useLiveSignals'
import { useSignalStore } from '../../stores/signal.store'
import { useDeviceStore } from '../../stores/device.store'

// On-device preview chrome — this overlay simulates a live device-side
// diagnostics page so every colour is a 1:1 mirror of the firmware palette.
// Kept as named constants for the planned token promotion (audit S-H-5,
// umbrella #1015). MUST stay literal — do NOT swap for studio chrome tokens
// without firmware review (preview-fidelity surface, see #957 / #1068).
const PANEL_BG = '#0D0D0D' // MIRROR: darker than --bg, device-page background
const HEADER_BORDER = '#2A2A2A' // MIRROR: between --bg and --surface
const ROW_BORDER = '#181818' // MIRROR: between --bg (#121212) and --surface (#1F1F1F)
const LABEL_FG = '#AAAAAA' // MIRROR: between --text-dim (#BABABA) and --text-muted (#8F8F8F)
const MUTED_FG = '#888888' // MIRROR: ≈ --text-muted (#8F8F8F), empty-state text
const DIM_FG = '#444444' // MIRROR: dim hint text (timestamp / swipe hint)
const UNIT_FG = '#555555' // MIRROR: dim variant of --text-muted
const NO_DATA_FG = '#555555' // MIRROR: same dim as UNIT_FG, "NO DATA" badge
const BAR_TRACK = '#1E1E1E' // MIRROR: between --bg and --surface, mini-bar track
const VALUE_FG = '#CCCCCC' // MIRROR: brighter than --text-dim, default value text
const SIM_FG = '#FF8800' // = --accent / --warning (#FF8800); kept literal to mirror firmware sim badge
const LIVE_FG = '#33CC55' // MIRROR: dimmer than --success (#00CC2A), firmware LIVE badge
const DANGER_FG = '#FF4444' // MIRROR: dimmer than --destructive (#FF0000), value-in-danger text
const DANGER_BAR = '#FF444488' // MIRROR: DANGER_FG with 53% alpha, mini-bar fill
const WARN_BAR = '#FF880088' // MIRROR: SIM_FG with 53% alpha, mini-bar fill
const OK_BAR = '#33CC5555' // MIRROR: LIVE_FG with 33% alpha, mini-bar fill

interface DiagnosticsPanelProps {
  scale: number
}

export default function DiagnosticsPanel({ scale }: DiagnosticsPanelProps) {
  const signals = useSignalStore((s) => s.signals)
  const connected = useDeviceStore((s) => s.connected)
  const simulationMode = useDeviceStore((s) => s.simulationMode)
  const values = useLiveSignals()
  const isLive = connected && !simulationMode

  const fs = Math.round(scale * 5.5)
  const pad = Math.round(scale * 6)
  const rowPad = Math.round(scale * 3)
  const barW = Math.round(scale * 32)
  const barH = Math.round(scale * 4)

  return (
    <div
      style={{
        position: 'absolute',
        inset: 0,
        background: PANEL_BG,
        zIndex: 100,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <div
        style={{
          padding: `${String(pad)}px ${String(pad)}px ${String(Math.round(scale * 3))}px`,
          borderBottom: `1px solid ${HEADER_BORDER}`,
          flexShrink: 0,
          display: 'flex',
          alignItems: 'baseline',
          gap: Math.round(scale * 4),
        }}
      >
        <span
          style={{
            fontSize: fs + 2,
            color: 'hsl(var(--text))',
            fontWeight: 600,
            letterSpacing: '0.08em',
            textTransform: 'uppercase',
          }}
        >
          Diagnostics
        </span>
        {/* Source badge */}
        <span
          style={{
            fontSize: fs - 1,
            color: isLive ? LIVE_FG : simulationMode ? SIM_FG : NO_DATA_FG,
            fontWeight: 600,
            letterSpacing: '0.06em',
          }}
        >
          {isLive ? 'LIVE' : simulationMode ? 'SIM' : 'NO DATA'}
        </span>
        <span style={{ fontSize: fs - 1, color: DIM_FG, marginLeft: 'auto' }}>
          swipe ↓ to close
        </span>
      </div>

      {/* Signal list */}
      <div style={{ overflowY: 'auto', flex: 1 }}>
        {signals.length === 0 ? (
          <div
            style={{
              padding: pad,
              fontSize: fs,
              color: MUTED_FG,
              textAlign: 'center',
              paddingTop: pad * 3,
            }}
          >
            No signals configured.
          </div>
        ) : (
          signals.map((sig) => {
            const raw = values[sig.name]
            const range = sig.max - sig.min || 1
            const pct = raw !== undefined ? Math.max(0, Math.min(1, (raw - sig.min) / range)) : null
            const isDanger = pct !== null && pct >= 0.95
            const isWarn = pct !== null && !isDanger && pct >= 0.8
            const valueColor = isDanger ? DANGER_FG : isWarn ? SIM_FG : VALUE_FG
            const barColor = isDanger ? DANGER_BAR : isWarn ? WARN_BAR : OK_BAR
            const valueStr = raw !== undefined ? raw.toFixed(1) : '—'

            return (
              <div
                key={sig.name}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  padding: `${String(rowPad)}px ${String(pad)}px`,
                  borderBottom: `1px solid ${ROW_BORDER}`,
                  gap: Math.round(scale * 3),
                }}
              >
                {/* Signal name */}
                <span
                  style={{
                    fontSize: fs,
                    color: LABEL_FG,
                    flex: 1,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {sig.name.replace(/_/g, ' ')}
                </span>

                {/* Mini bar */}
                <div
                  style={{
                    width: barW,
                    height: barH,
                    background: BAR_TRACK,
                    borderRadius: 2,
                    flexShrink: 0,
                    overflow: 'hidden',
                  }}
                >
                  {pct !== null && (
                    <div
                      style={{
                        width: `${String(Math.round(pct * 100))}%`,
                        height: '100%',
                        background: barColor,
                        borderRadius: 2,
                        transition: 'width 0.25s linear',
                      }}
                    />
                  )}
                </div>

                {/* Value */}
                <span
                  style={{
                    fontSize: fs,
                    color: valueColor,
                    fontVariantNumeric: 'tabular-nums',
                    minWidth: Math.round(scale * 18),
                    textAlign: 'right',
                    flexShrink: 0,
                  }}
                >
                  {valueStr}
                </span>

                {/* Unit */}
                <span
                  style={{
                    fontSize: fs - 1,
                    color: UNIT_FG,
                    minWidth: Math.round(scale * 10),
                    flexShrink: 0,
                  }}
                >
                  {sig.unit}
                </span>
              </div>
            )
          })
        )}
      </div>
    </div>
  )
}
