import type { DashboardConfig } from '@canshift/core'
import { DEFAULT_PAGE_PALETTE, CURRENT_SCHEMA_VERSION, DashboardConfigSchema } from '@canshift/core'

const PARSED_SIM_CONFIG = DashboardConfigSchema.parse({
  version: CURRENT_SCHEMA_VERSION,
  ...{
    name: 'CANShift',
    description:
      'Six-page default dashboard \u2014 street, track, engine, tuning, timing, controls',
    defaultPageId: 'street',
    revLimitRpm: 7200,
    topBar: {
      height: 16,
      bgColor: '#0D0D0D',
      textColor: '#AAAAAA',
      layout: [
        {
          type: 'label',
          text: 'CAN',
          position: 'left',
        },
        {
          type: 'statusDot',
          signal: 'any',
          position: 'left',
        },
        {
          type: 'modeFlag',
          signal: 'flag_anti_lag',
          text: 'ALS',
          position: 'center',
        },
        {
          type: 'separator',
          position: 'center',
        },
        {
          type: 'modeFlag',
          signal: 'flag_launch_ctrl',
          text: 'LC',
          position: 'center',
        },
        {
          type: 'separator',
          position: 'center',
        },
        {
          type: 'modeFlag',
          signal: 'flag_flat_shift',
          text: 'FS',
          position: 'center',
        },
        {
          type: 'separator',
          position: 'center',
        },
        {
          type: 'modeFlag',
          signal: 'flag_traction_cut',
          text: 'TC',
          position: 'center',
        },
        {
          type: 'signal',
          signal: 'map_number',
          format: 'MAP%.0f',
          position: 'right',
        },
        {
          type: 'separator',
          position: 'right',
        },
        {
          type: 'bleIcon',
          position: 'right',
        },
        {
          type: 'themeToggle',
          position: 'right',
        },
      ],
    },
    dayTheme: {
      bgColor: '#E8E8E8',
    },
    pages: [
      {
        id: 'street',
        backgroundImage: null,
        backgroundColor: '#000000',
        showTopBar: true,
        widgets: [
          {
            id: 'street_speed',
            type: 'gauge',
            signal: 'speed_kph',
            layout: {
              col: 0,
              colSpan: 7,
              row: 0,
              rowSpan: 5,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FFFFFF',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 48,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'speed',
              minValue: 0,
              maxValue: 300,
              dangerLevel: 280,
              decimalPlaces: 0,
            },
          },
          {
            id: 'street_gear',
            type: 'gear',
            signal: 'gear',
            layout: {
              col: 7,
              colSpan: 5,
              row: 0,
              rowSpan: 5,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 48,
            },
            config: {
              type: 'gear',
              decimalPlaces: 0,
            },
          },
          {
            id: 'street_rpm',
            type: 'gauge',
            signal: 'rpm',
            layout: {
              col: 0,
              colSpan: 6,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'rpm',
              minValue: 0,
              maxValue: 8000,
              dangerLevel: 7000,
              decimalPlaces: 0,
            },
          },
          {
            id: 'street_water',
            type: 'gauge',
            signal: 'coolant_temp_c',
            layout: {
              col: 6,
              colSpan: 3,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#44AAFF',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 22,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'coolant',
              minValue: 0,
              maxValue: 120,
              dangerLevel: 110,
              decimalPlaces: 0,
            },
          },
          {
            id: 'street_fuel',
            type: 'gauge',
            signal: 'fuel_press_bar',
            layout: {
              col: 9,
              colSpan: 3,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 22,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'fuel',
              minValue: 0,
              maxValue: 6,
              dangerLevel: 5.5,
              decimalPlaces: 1,
            },
          },
          {
            id: 'street_batt',
            type: 'gauge',
            signal: 'battery_volts',
            layout: {
              col: 0,
              colSpan: 4,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FBC02D',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 22,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'battery',
              minValue: 10,
              maxValue: 15,
              dangerLevel: 14.8,
              decimalPlaces: 1,
            },
          },
          {
            id: 'street_to_track',
            type: 'button',
            signal: '',
            layout: {
              col: 4,
              colSpan: 8,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 14,
            },
            config: {
              type: 'button',
              mode: 'single',
              label: 'TRACK',
              iconName: 'cog',
              showLabel: true,
              showIcon: false,
              actions: [
                {
                  category: 'dashboard',
                  type: 'navigate',
                  pageId: 'track',
                },
              ],
            },
          },
        ],
        palette: { ...DEFAULT_PAGE_PALETTE },
      },
      {
        id: 'track',
        backgroundImage: null,
        backgroundColor: '#000000',
        showTopBar: true,
        widgets: [
          {
            id: 'track_shift',
            type: 'shift_light',
            signal: 'rpm',
            layout: {
              col: 0,
              colSpan: 12,
              row: 0,
              rowSpan: 1,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FFFFFF',
              secondaryColor: '#222222',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 16,
            },
            config: {
              type: 'shift_light',
              startValue: 3000,
              redSegments: 5,
            },
          },
          {
            id: 'track_rpm',
            type: 'gauge',
            signal: 'rpm',
            layout: {
              col: 0,
              colSpan: 7,
              row: 1,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 48,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'rpm',
              minValue: 0,
              maxValue: 8000,
              dangerLevel: 7000,
              decimalPlaces: 0,
            },
          },
          {
            id: 'track_gear',
            type: 'gear',
            signal: 'gear',
            layout: {
              col: 7,
              colSpan: 5,
              row: 1,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 48,
            },
            config: {
              type: 'gear',
              decimalPlaces: 0,
            },
          },
          {
            id: 'track_speed',
            type: 'gauge',
            signal: 'speed_kph',
            layout: {
              col: 0,
              colSpan: 6,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FFFFFF',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'speed',
              minValue: 0,
              maxValue: 300,
              dangerLevel: 280,
              decimalPlaces: 0,
            },
          },
          {
            id: 'track_oilp',
            type: 'gauge',
            signal: 'oil_press_bar',
            layout: {
              col: 6,
              colSpan: 6,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'oil_pressure',
              minValue: 0,
              maxValue: 6,
              dangerLevel: 5.8,
              decimalPlaces: 1,
            },
          },
          {
            id: 'track_water',
            type: 'gauge',
            signal: 'coolant_temp_c',
            layout: {
              col: 0,
              colSpan: 3,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#44AAFF',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 20,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'coolant',
              minValue: 0,
              maxValue: 120,
              dangerLevel: 110,
              decimalPlaces: 0,
            },
          },
          {
            id: 'track_oilt',
            type: 'gauge',
            signal: 'oil_temp_c',
            layout: {
              col: 3,
              colSpan: 3,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 20,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'oil_temp',
              minValue: 0,
              maxValue: 150,
              dangerLevel: 140,
              decimalPlaces: 0,
            },
          },
          {
            id: 'track_map',
            type: 'gauge',
            signal: 'map_kpa',
            layout: {
              col: 6,
              colSpan: 3,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 20,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'boost',
              minValue: 0,
              maxValue: 300,
              dangerLevel: 270,
              decimalPlaces: 0,
            },
          },
          {
            id: 'track_batt',
            type: 'gauge',
            signal: 'battery_volts',
            layout: {
              col: 9,
              colSpan: 3,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FBC02D',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 20,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'battery',
              minValue: 10,
              maxValue: 15,
              dangerLevel: 14.8,
              decimalPlaces: 1,
            },
          },
        ],
        palette: { ...DEFAULT_PAGE_PALETTE },
      },
      {
        id: 'engine',
        backgroundImage: null,
        backgroundColor: '#000000',
        showTopBar: true,
        widgets: [
          {
            id: 'eng_water',
            type: 'gauge',
            signal: 'coolant_temp_c',
            layout: {
              col: 0,
              colSpan: 6,
              row: 0,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#44AAFF',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'coolant',
              minValue: 0,
              maxValue: 120,
              dangerLevel: 110,
              decimalPlaces: 0,
            },
          },
          {
            id: 'eng_oilt',
            type: 'gauge',
            signal: 'oil_temp_c',
            layout: {
              col: 6,
              colSpan: 6,
              row: 0,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'oil_temp',
              minValue: 0,
              maxValue: 150,
              dangerLevel: 140,
              decimalPlaces: 0,
            },
          },
          {
            id: 'eng_oilp',
            type: 'gauge',
            signal: 'oil_press_bar',
            layout: {
              col: 0,
              colSpan: 6,
              row: 4,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'oil_pressure',
              minValue: 0,
              maxValue: 6,
              dangerLevel: 5.8,
              decimalPlaces: 1,
            },
          },
          {
            id: 'eng_fuelp',
            type: 'gauge',
            signal: 'fuel_press_bar',
            layout: {
              col: 6,
              colSpan: 6,
              row: 4,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'fuel',
              minValue: 0,
              maxValue: 6,
              dangerLevel: 5.5,
              decimalPlaces: 1,
            },
          },
          {
            id: 'eng_iat',
            type: 'gauge',
            signal: 'iat_c',
            layout: {
              col: 0,
              colSpan: 4,
              row: 8,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#4FC3F7',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 22,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'iat',
              minValue: -20,
              maxValue: 80,
              dangerLevel: 60,
              decimalPlaces: 0,
            },
          },
          {
            id: 'eng_map',
            type: 'gauge',
            signal: 'map_kpa',
            layout: {
              col: 4,
              colSpan: 4,
              row: 8,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 22,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'boost',
              minValue: 0,
              maxValue: 300,
              dangerLevel: 270,
              decimalPlaces: 0,
            },
          },
          {
            id: 'eng_batt',
            type: 'gauge',
            signal: 'battery_volts',
            layout: {
              col: 8,
              colSpan: 4,
              row: 8,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FBC02D',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 22,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'battery',
              minValue: 10,
              maxValue: 15,
              dangerLevel: 14.8,
              decimalPlaces: 1,
            },
          },
        ],
        palette: { ...DEFAULT_PAGE_PALETTE },
      },
      {
        id: 'tuning',
        backgroundImage: null,
        backgroundColor: '#000000',
        showTopBar: true,
        widgets: [
          {
            id: 'tune_boost',
            type: 'gauge',
            signal: 'map_kpa',
            layout: {
              col: 0,
              colSpan: 7,
              row: 0,
              rowSpan: 5,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 48,
            },
            config: {
              type: 'gauge',
              displayStyle: 'arc',
              iconName: 'boost',
              minValue: 0,
              maxValue: 300,
              dangerLevel: 270,
              decimalPlaces: 0,
            },
          },
          {
            id: 'tune_lambda',
            type: 'gauge',
            signal: 'lambda_1',
            layout: {
              col: 7,
              colSpan: 5,
              row: 0,
              rowSpan: 5,
              zOrder: 0,
            },
            style: {
              primaryColor: '#44CC88',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'afr',
              minValue: 0.7,
              maxValue: 1.3,
              dangerLevel: 1.2,
              decimalPlaces: 2,
            },
          },
          {
            id: 'tune_tps',
            type: 'gauge',
            signal: 'throttle_pos',
            layout: {
              col: 0,
              colSpan: 6,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              showBar: true,
              iconName: 'throttle',
              minValue: 0,
              maxValue: 100,
              dangerLevel: 95,
              decimalPlaces: 0,
            },
          },
          {
            id: 'tune_iat',
            type: 'gauge',
            signal: 'iat_c',
            layout: {
              col: 6,
              colSpan: 6,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#4FC3F7',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'iat',
              minValue: -20,
              maxValue: 80,
              dangerLevel: 60,
              decimalPlaces: 0,
            },
          },
          {
            id: 'tune_rpm',
            type: 'gauge',
            signal: 'rpm',
            layout: {
              col: 0,
              colSpan: 4,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 20,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'rpm',
              minValue: 0,
              maxValue: 8000,
              dangerLevel: 7000,
              decimalPlaces: 0,
            },
          },
          {
            id: 'tune_fuelp',
            type: 'gauge',
            signal: 'fuel_press_bar',
            layout: {
              col: 4,
              colSpan: 4,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF8800',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 20,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'fuel',
              minValue: 0,
              maxValue: 6,
              dangerLevel: 5.5,
              decimalPlaces: 1,
            },
          },
          {
            id: 'tune_batt',
            type: 'gauge',
            signal: 'battery_volts',
            layout: {
              col: 8,
              colSpan: 4,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FBC02D',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 20,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'battery',
              minValue: 10,
              maxValue: 15,
              dangerLevel: 14.8,
              decimalPlaces: 1,
            },
          },
        ],
        palette: { ...DEFAULT_PAGE_PALETTE },
      },
      {
        id: 'timing',
        backgroundImage: null,
        backgroundColor: '#000000',
        showTopBar: true,
        widgets: [
          {
            id: 'timing_timer',
            type: 'timer',
            signal: '',
            layout: {
              col: 0,
              colSpan: 7,
              row: 0,
              rowSpan: 5,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FFFFFF',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 48,
            },
            config: {
              type: 'timer',
              autoStart: false,
              format: 'mm:ss',
            },
          },
          {
            id: 'timing_gear',
            type: 'gear',
            signal: 'gear',
            layout: {
              col: 7,
              colSpan: 5,
              row: 0,
              rowSpan: 5,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 48,
            },
            config: {
              type: 'gear',
              decimalPlaces: 0,
            },
          },
          {
            id: 'timing_speed',
            type: 'gauge',
            signal: 'speed_kph',
            layout: {
              col: 0,
              colSpan: 6,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FFFFFF',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'speed',
              minValue: 0,
              maxValue: 300,
              dangerLevel: 280,
              decimalPlaces: 0,
            },
          },
          {
            id: 'timing_rpm',
            type: 'gauge',
            signal: 'rpm',
            layout: {
              col: 6,
              colSpan: 6,
              row: 5,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 28,
            },
            config: {
              type: 'gauge',
              displayStyle: 'numeric',
              iconName: 'rpm',
              minValue: 0,
              maxValue: 8000,
              dangerLevel: 7000,
              decimalPlaces: 0,
            },
          },
          {
            id: 'timing_to_street',
            type: 'button',
            signal: '',
            layout: {
              col: 0,
              colSpan: 12,
              row: 9,
              rowSpan: 3,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 14,
            },
            config: {
              type: 'button',
              mode: 'single',
              label: 'STREET',
              iconName: 'cog',
              showLabel: true,
              showIcon: false,
              actions: [
                {
                  category: 'dashboard',
                  type: 'navigate',
                  pageId: 'street',
                },
              ],
            },
          },
        ],
        palette: { ...DEFAULT_PAGE_PALETTE },
      },
      {
        id: 'controls',
        backgroundImage: null,
        backgroundColor: '#000000',
        showTopBar: true,
        widgets: [
          {
            id: 'btn_map_cycle',
            type: 'button',
            signal: '',
            layout: {
              col: 0,
              colSpan: 12,
              row: 0,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4444',
              secondaryColor: '#1A1A1A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 16,
            },
            config: {
              type: 'button',
              mode: 'cycle',
              label: 'MAP',
              iconName: 'map_icon',
              showLabel: true,
              showIcon: true,
              colors: {
                normal: '#3A1212',
                active: '#FF4444',
              },
              initialActiveIndex: 0,
              states: [
                {
                  label: 'MAP 1',
                  action: {
                    category: 'ecu',
                    type: 'map_switch',
                    mapIndex: 1,
                  },
                },
                {
                  label: 'MAP 2',
                  action: {
                    category: 'ecu',
                    type: 'map_switch',
                    mapIndex: 2,
                  },
                },
                {
                  label: 'MAP 3',
                  action: {
                    category: 'ecu',
                    type: 'map_switch',
                    mapIndex: 3,
                  },
                },
              ],
            },
          },
          {
            id: 'btn_launch',
            type: 'button',
            signal: 'flag_launch_ctrl',
            layout: {
              col: 0,
              colSpan: 6,
              row: 4,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4444',
              secondaryColor: '#1A1A1A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 16,
            },
            config: {
              type: 'button',
              mode: 'single',
              label: 'Launch',
              iconName: 'launch',
              showLabel: true,
              showIcon: true,
              isToggle: true,
              colors: {
                normal: '#1F1F1F',
                active: '#43A047',
              },
              actions: [
                {
                  category: 'ecu',
                  type: 'can_raw',
                  frameId: 1312,
                  data: '01',
                  dataOff: '00',
                },
              ],
            },
          },
          {
            id: 'btn_antilag',
            type: 'button',
            signal: 'flag_anti_lag',
            layout: {
              col: 6,
              colSpan: 6,
              row: 4,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4444',
              secondaryColor: '#1A1A1A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 16,
            },
            config: {
              type: 'button',
              mode: 'single',
              label: 'Anti-lag',
              iconName: 'flame',
              showLabel: true,
              showIcon: true,
              isToggle: true,
              colors: {
                normal: '#1F1F1F',
                active: '#FF6F00',
              },
              actions: [
                {
                  category: 'ecu',
                  type: 'can_raw',
                  frameId: 1313,
                  data: '01',
                  dataOff: '00',
                },
              ],
            },
          },
          {
            id: 'btn_traction',
            type: 'button',
            signal: 'flag_traction_cut',
            layout: {
              col: 0,
              colSpan: 6,
              row: 8,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 16,
            },
            config: {
              type: 'button',
              mode: 'single',
              label: 'Traction cut',
              iconName: 'cog',
              showLabel: true,
              showIcon: false,
              isToggle: true,
              colors: {
                normal: '#1F1F1F',
                active: '#FF6F00',
              },
              actions: [
                {
                  category: 'ecu',
                  type: 'can_raw',
                  frameId: 1314,
                  data: '01',
                  dataOff: '00',
                },
              ],
            },
          },
          {
            id: 'controls_to_street',
            type: 'button',
            signal: '',
            layout: {
              col: 6,
              colSpan: 6,
              row: 8,
              rowSpan: 4,
              zOrder: 0,
            },
            style: {
              primaryColor: '#FF4747',
              secondaryColor: '#2A2A2A',
              warningColor: '#FF8800',
              criticalColor: '#FF4444',
              textColor: '#FFFFFF',
              fontSize: 14,
            },
            config: {
              type: 'button',
              mode: 'single',
              label: 'STREET',
              iconName: 'cog',
              showLabel: true,
              showIcon: false,
              actions: [
                {
                  category: 'dashboard',
                  type: 'navigate',
                  pageId: 'street',
                },
              ],
            },
          },
        ],
        palette: { ...DEFAULT_PAGE_PALETTE },
      },
    ],
  },
})

export const DEFAULT_SIM_CONFIG: DashboardConfig = PARSED_SIM_CONFIG as DashboardConfig
