#!/usr/bin/env node
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = resolve(SCRIPT_DIR, '..')
const CORE_PKG_DIR = resolve(PKG_ROOT, 'node_modules', '@tmbk', 'canshift-core')
const CORE_TOKENS_JS = resolve(CORE_PKG_DIR, 'dist', 'design-tokens.js')
const OUTPUT_PATH = resolve(PKG_ROOT, 'src', 'styles', 'tokens.generated.css')

const HEADER = [
  '/* AUTO-GENERATED by scripts/generate-tokens.css.ts — DO NOT EDIT BY HAND */',
  '/* Source of truth: canshift-core/src/design-tokens.ts (DARK_TOKENS) */',
  '',
].join('\n')

const buildCss = (cssVars) => {
  const lines = [':root {']
  for (const [name, value] of Object.entries(cssVars)) {
    lines.push(`  ${name}: ${value};`)
  }
  lines.push('}', '')
  return `${HEADER}\n${lines.join('\n')}`
}

const writeIfChanged = (path, content) => {
  if (existsSync(path)) {
    const previous = readFileSync(path, 'utf8')
    if (previous === content) return false
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, 'utf8')
  return true
}

const main = async () => {
  if (!existsSync(CORE_TOKENS_JS)) {
    throw new Error(
      `canshift-core build artifact not found at ${CORE_TOKENS_JS}. ` +
        `Run \`npm --prefix ../canshift-core run build\` first (predev/prebuild does this automatically).`
    )
  }
  const { DARK_TOKENS, tokensToCssVars } = await import(pathToFileURL(CORE_TOKENS_JS).href)
  const cssVars = tokensToCssVars(DARK_TOKENS)
  const css = buildCss(cssVars)
  const changed = writeIfChanged(OUTPUT_PATH, css)
  const rel = OUTPUT_PATH.replace(`${PKG_ROOT}/`, '')
  console.log(changed ? `[tokens:gen] wrote ${rel}` : `[tokens:gen] up to date — ${rel}`)
}

try {
  await main()
} catch (err) {
  const message = err instanceof Error ? err.message : String(err)
  console.error(`[tokens:gen] error: ${message}`)
  process.exit(1)
}
