#!/usr/bin/env node
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = resolve(SCRIPT_DIR, '..')
const OUTPUT_PATH = resolve(PKG_ROOT, 'src', 'styles', 'tokens.generated.css')

const HEADER = [
  '/* AUTO-GENERATED by scripts/generate-tokens.css.ts — DO NOT EDIT BY HAND */',
  '/* Source of truth: @canshift/core (DARK_TOKENS + BRAND_TOKENS + FONT_TOKENS) */',
  '',
].join('\n')

const buildCss = (cssVars, lightCssVars) => {
  const lines = [':root {']
  for (const [name, value] of Object.entries(cssVars)) {
    lines.push(`  ${name}: ${value};`)
  }
  lines.push('}', '', ":root[data-theme='light'] {")
  for (const [name, value] of Object.entries(lightCssVars)) {
    lines.push(`  ${name}: ${value};`)
  }
  lines.push('}', '')
  return `${HEADER}\n${lines.join('\n')}`
}

const writeIfChanged = (path, content) => {
  if (existsSync(path)) {
    const previous = readFileSync(path, 'utf8')
    if (previous === content) return false
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, 'utf8')
  return true
}

const main = async () => {
  const {
    DARK_TOKENS,
    BRAND_TOKENS,
    FONT_TOKENS,
    tokensToCssVars,
    brandTokensToCssVars,
    brandLightThemeCssVars,
    fontTokensToCssVars,
  } = await import('@canshift/core')
  const cssVars = {
    ...tokensToCssVars(DARK_TOKENS),
    ...brandTokensToCssVars(BRAND_TOKENS),
    ...fontTokensToCssVars(FONT_TOKENS),
  }
  const css = buildCss(cssVars, brandLightThemeCssVars(BRAND_TOKENS))
  const changed = writeIfChanged(OUTPUT_PATH, css)
  const rel = OUTPUT_PATH.replace(`${PKG_ROOT}/`, '')
  console.log(changed ? `[tokens:gen] wrote ${rel}` : `[tokens:gen] up to date — ${rel}`)
}

try {
  await main()
} catch (err) {
  const message = err instanceof Error ? err.message : String(err)
  console.error(`[tokens:gen] error: ${message}`)
  process.exit(1)
}
